version: '3.9'

services:
  control:
    container_name: control
    hostname: control
    image: ansible_base:latest
    tty: true
    privileged: true # Required for /usr/sbin/init
    volumes:
      - ./work:/work
  lb01:
    container_name: lb01
    hostname: lb01
    image: ansible_base:latest
    tty: true
    privileged: true
  app01:
    container_name: app01
    hostname: app01
    image: ansible_base:latest
    tty: true
    privileged: true
  app02:
    container_name: app02
    hostname: app02
    image: ansible_base:latest
    tty: true
    privileged: true
  db01:
    container_name: db01
    hostname: db01
    image: ansible_base:latest
    tty: true
    privileged: true
